name: "publish"

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v5

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: npm ci

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Bump version
        run: npm version patch --no-git-tag-version

      - name: Calculate version
        id: calculateVersion
        run: |
          APP_VERSION=`cat package.json | jq ".version" -M | sed 's/\"//g'`
          echo "AppVersion=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "app version = v$APP_VERSION"

      - name: Commit and push version bump
        run: |
          git add package.json
          git commit -m "chore: bump version to ${{ steps.calculateVersion.outputs.AppVersion }} [skip ci]"
          git push

      - name: Build backend package
        working-directory: ./src/backend
        run: ./create-packages.sh

      - name: Build VSIX package
        run: vsce package -o vscode-starlims.v${{ steps.calculateVersion.outputs.AppVersion }}.vsix

      - name: Publish extension package
        run: vsce publish -p $VSCODE_MARKETPLACE_TOKEN --packagePath vscode-starlims.v${{ steps.calculateVersion.outputs.AppVersion }}.vsix
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}

      - uses: rickstaa/action-create-tag@v1
        name: Create tag
        with:
          tag: v${{ steps.calculateVersion.outputs.AppVersion }}
          tag_exists_error: false
          message: "Latest release"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.calculateVersion.outputs.AppVersion }}
          name: v${{ steps.calculateVersion.outputs.AppVersion }}
          artifacts: "vscode-starlims.v${{ steps.calculateVersion.outputs.AppVersion }}.vsix,src/backend/SCM_API.sdp"
          makeLatest: true
